version: '3.0'

services:
  jenkins:
    container_name: jenkins
    restart: always
    build: .
    ports:
      - "8087:8080"
      - "50000:50000"
    dns:
      - 8.8.8.8
    networks:
      - jenkins
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ./jenkins-docker-certs:/certs/client
      - ./jenkins-data:/var/jenkins_home
  
  agent:
    container_name: agent
    image: jenkins/ssh-agent:latest-jdk11
    user: root
    expose:
      - 22
    #environment:
    #  JENKINS_AGENT_SSH_PUBKEY: ${SSH_PUB_KEY} 
volumes:
  jenkins-docker-certs:
  jenkins-data:
networks:
  jenkins:
    name: docker